name: php-cs-fixer

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        name: php-cs-fixer

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: php-cs-fixer
                uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
                with:
                    args: fix --diff --dry-run
