name: phpstan

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        name: phpstan

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Cache dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-11.*-php-8.3-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    coverage: pcov

            -   name: Install dependencies
                run: |
                    composer update --prefer-dist --no-interaction

            -   name: Run phpstan
                run: vendor/bin/phpstan
